@host=http://localhost:8088/api/v1
# @host=http://106.13.92.185:8088/api/v1
@token={{loginAPI.response.body.token}}
###
POST {{host}}/user/test
Content-Type: application/json

{
  "test":"测试成功了哈哈"
}

### 根据Token获取用户信息
GET {{host}}/user/getuser
Authorization: {{token}}

### 登陆(只能获取Token)
# @name loginAPI
POST {{host}}/user/login
Content-Type: application/json

{
    "email": "l.7@qq.com",
    "password": "yangqi77"
}

### 注册用户
POST {{host}}/user/register
Content-Type: application/json

{
    "name": "sssss",
    "email": "l.77777@qq.com",
    "password": "yangqi77",
    "password2": "yangqi77",
    "avatar":"头像地址"
}